In [15]:
import numpy as np

# 加载.npy文件
data = np.load('/home/qianghuang/CausalTransformer-main/multirun/2023-06-07/14-32-29/0/predictions_multi_steps.npz')
# 打印加载的数据
print(data.files)
data['output'][0:20]

['means', 'output', 'active_entries', 'treatments']


array([[[0.05474594],
        [0.0552498 ],
        [0.05884946],
        [0.06355067],
        [0.0694424 ]],

       [[0.06441914],
        [0.05990619],
        [0.06143539],
        [0.06512453],
        [0.07051448]],

       [[0.06441914],
        [0.06992567],
        [0.06617351],
        [0.06752901],
        [0.07178262]],

       [[0.06441914],
        [0.06992567],
        [0.07704946],
        [0.07252827],
        [0.0742291 ]],

       [[0.06441914],
        [0.06992567],
        [0.07704946],
        [0.08451222],
        [0.07980326]],

       [[0.03962434],
        [0.04318797],
        [0.04777862],
        [0.05261564],
        [0.05809615]],

       [[0.06441914],
        [0.04424325],
        [0.04893628],
        [0.05387975],
        [0.05948021]],

       [[0.06441914],
        [0.06992567],
        [0.04917171],
        [0.0541368 ],
        [0.05976162]],

       [[0.06441914],
        [0.06992567],
        [0.07704946],
        [0.05379438],
        [0.05938

In [7]:
import yaml
with open('/home/qianghuang/CausalTransformer-main/config/config.yaml', 'r') as file:
    data = yaml.load(file, Loader=yaml.FullLoader)
data['exp']['radio']


4

In [36]:
num = []
for i in range(20):
    file = open('/home/qianghuang/CausalTransformer-main/multirun/2023-06-07/14-37-48/'+str(i)+'/train_enc_dec.log','r')
    # file = open('/home/qianghuang/CausalTransformer-main/multirun/2023-06-07/14-40-51/'+str(i)+'/train_rmsn.log','r')
    # file = open('/home/qianghuang/CausalTransformer-main/multirun/2023-06-07/14-36-09/'+str(i)+'/train_gnet.log','r')
    line = file.readlines()[-1].strip()
    index = line.find("{'2-step':")
    dict_num = line[index:]
    my_dict = eval(dict_num)
    dict_values = my_dict.values()
    # print(my_dict)
    # print(list(dict_values))
    num.extend(dict_values)
num = np.array(num).reshape(4,5,5)
num = np.transpose(num,axes=(0, 2, 1))
mean_values = np.mean(num, axis=2)
std_values = np.std(num, axis=2)
print(mean_values)
print(std_values)
for i in range(4):
    print()
    for j in range(0,5):
        print("gamma "+str(i)+", step "+str(j+2)+" mean and std:"+ str(mean_values[i][j].round(4))+"+-"+str(std_values[i][j].round(4)))

[[0.68361505 0.69604753 0.71628893 0.73996812 0.76788545]
 [0.66867046 0.689564   0.71235278 0.73655112 0.76324783]
 [0.75973408 0.8178207  0.86919631 0.91074351 0.94361606]
 [1.49263825 2.13529005 2.35761505 2.5052607  2.62445058]]
[[0.04975761 0.0472959  0.04738954 0.05012232 0.05135459]
 [0.04735582 0.04627749 0.05098558 0.0526093  0.05064625]
 [0.04641532 0.05880858 0.0781406  0.08451434 0.09848505]
 [0.82792736 1.66943    1.83143596 1.94652214 2.10903989]]

gamma 0, step 2 mean and std:0.6836+-0.0498
gamma 0, step 3 mean and std:0.696+-0.0473
gamma 0, step 4 mean and std:0.7163+-0.0474
gamma 0, step 5 mean and std:0.74+-0.0501
gamma 0, step 6 mean and std:0.7679+-0.0514

gamma 1, step 2 mean and std:0.6687+-0.0474
gamma 1, step 3 mean and std:0.6896+-0.0463
gamma 1, step 4 mean and std:0.7124+-0.051
gamma 1, step 5 mean and std:0.7366+-0.0526
gamma 1, step 6 mean and std:0.7632+-0.0506

gamma 2, step 2 mean and std:0.7597+-0.0464
gamma 2, step 3 mean and std:0.8178+-0.0588
gamma 2

In [2]:
# data_static = np.load('/home/qianghuang/CausalTransformer-main/multirun/2023-06-06/13-42-06/0/multi_statics.npz')
# print(data_static.files)

# print(data_static['num_patients'])
# print(data_static['num_test_points'])
# print(data_static['seq_length'])
# print(data_static['horizon'])
treatment_seq = np.load('/home/qianghuang/CausalTransformer-main/multirun/2023-06-07/14-34-23/0/test_cf_treatment_seq.npz')
print(treatment_seq.files)
patient_i = treatment_seq['patient_ids_all_trajectories']
patient_t=treatment_seq['patient_current_t']
# for i in range(59):
    # print(np.count_nonzero(patient_t==i))
# for i in range(1000):
#     print(np.count_nonzero(patient_i==i))
i_t = np.concatenate([patient_i.reshape(-1,1),patient_t.reshape(-1,1)],axis=1)
index_per_patients = [-1]
for i in range(i_t.shape[0]-1):
    if np.all(i_t[i] == i_t[i+1]):
        None
    else:
        index_per_patients.append(i)
index_per_patients.append(len(patient_i)-1)

index_per_patients=list(np.array(index_per_patients)+1)
print(index_per_patients)

['cancer_volume', 'chemo_application', 'radio_application', 'sequence_lengths', 'patient_types', 'patient_ids_all_trajectories', 'patient_current_t']
[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190, 1200, 1210, 1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320, 1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430, 1440, 1450, 1460, 1470, 1480, 1490, 1500, 1510, 1520, 1530, 1540, 1550, 1560, 1570, 1580, 1590, 

In [8]:
## for timing accuarcy
predict_outcomes = data['means'].squeeze()
ground_outcomes = data['output'].squeeze()
activate_entries = data['active_entries'].squeeze()
treatments = data['treatments']
# print(predict_outcomes.shape)
# print(ground_outcomes.shape)
# print(activate_entries.shape)
# print(treatments.shape)
# treatments[:10,:,:]
timing_predict_all = []
timing_ground_all = []
for i in range(len(index_per_patients)-1):
    predict_outcome_seq_last = predict_outcomes[index_per_patients[i]:index_per_patients[i+1],:][:,4]
    idx_seq = np.argmin(predict_outcome_seq_last)
    target_treatments = treatments[index_per_patients[i]+idx_seq,:,:]
    if i==0:
        print(target_treatments)
    timing_predict=np.where(~np.all(target_treatments == [1, 0, 0, 0], axis=1))[0][0]
    timing_predict_all.append(timing_predict)

    ground_outcome_seq_last = ground_outcomes[index_per_patients[i]:index_per_patients[i+1],:][:,4]
    idx_seq = np.argmin(ground_outcome_seq_last)
    target_treatments = treatments[index_per_patients[i]+idx_seq,:,:]
    timing_ground = np.where(~np.all(target_treatments == [1, 0, 0, 0], axis=1))[0][0]
    timing_ground_all.append(timing_ground)
print(timing_predict_all)
print(timing_ground_all)

print(np.argmin(predict_outcomes[:10,4]))
# print(treatments[:10])
# predict_outcomes[:10]
# print(ground_outcomes)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
[3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 0, 0, 0, 3, 3, 3, 3, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,

In [13]:
## for timing accuarcy
predict_outcomes = data['means'].squeeze()
ground_outcomes = data['output'].squeeze()
activate_entries = data['active_entries'].squeeze()
treatments = data['treatments']
# print(predict_outcomes.shape)
# print(ground_outcomes.shape)
# print(activate_entries.shape)
# print(treatments.shape)
# treatments[:10,:,:]
type_predict_all = []
type_ground_all = []
for i in range(len(index_per_patients)-1):
    predict_outcome_seq_last = predict_outcomes[index_per_patients[i]:index_per_patients[i+1],:][:,4]
    idx_seq = np.argmin(predict_outcome_seq_last)
    target_treatments = treatments[index_per_patients[i]+idx_seq,:,:]
    if i==1:
        print(target_treatments)
    type_predict_idx=np.where(~np.all(target_treatments == [1, 0, 0, 0], axis=1))[0][0]
    if np.all(target_treatments[type_predict_idx]==[0,1,0,0]):
        type_predict_all.append(0)
    else:
        type_predict_all.append(1)


    ground_outcome_seq_last = ground_outcomes[index_per_patients[i]:index_per_patients[i+1],:][:,4]
    idx_seq = np.argmin(ground_outcome_seq_last)
    target_treatments = treatments[index_per_patients[i]+idx_seq,:,:]
    if i==1:
        print(target_treatments)
    type_ground_idx = np.where(~np.all(target_treatments == [1, 0, 0, 0], axis=1))[0][0]
    if np.all(target_treatments[type_ground_idx]==[0,1,0,0]):
        type_ground_all.append(0)
    else:
        type_ground_all.append(1)
print(type_predict_all)
print(type_ground_all)
type_ground_all = np.array(type_ground_all)
type_predict_all = np.array(type_predict_all)
print((type_ground_all==type_predict_all).sum()/len(type_ground_all))
# print(np.argmin(predict_outcomes[:10,4]))
# print(treatments[:10])
# predict_outcomes[:10]
# print(ground_outcomes)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [11]:
timing_ground_all = np.array(timing_ground_all)
timing_predict_all = np.array(timing_predict_all)
(timing_ground_all==timing_predict_all).sum()/len(timing_ground_all)

0.10590651474160233

In [12]:
print(predict_outcomes.shape)
print(ground_outcomes.shape)
print(activate_entries.shape)
print(treatments.shape)
treatments[:10,:,:]
# ground_outcomes
# predict_outcomes

(506363, 5)
(506363, 5)
(506363, 5)
(506363, 5, 4)


array([[[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]],

       [[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.]

In [13]:
num_samples, time_dim, output_dim = activate_entries.shape
last_entries = activate_entries - np.concatenate([activate_entries[:, 1:, :], np.zeros((num_samples, 1, output_dim))], axis=1)
last_entries.shape
# last_predict_outcomes = predict_outcomes * last_entries
# last_ground_outcomes = ground_outcomes * last_entries
treatments
treatments_2 = treatments[:,0,:]
treatments_3 = treatments[:,1,:]
treatments_4 = treatments[:,2,:]
treatments_2.shape

ValueError: not enough values to unpack (expected 3, got 2)

In [ ]:
# 得到不同treatment combination的索引
indices_1000 = np.where(np.all(treatments_3 == [1, 0, 0, 0], axis=1))[0]
indices_0100 = np.where(np.all(treatments_3 == [0, 1, 0, 0], axis=1))[0]
indices_0010 = np.where(np.all(treatments_3 == [0, 0, 1, 0], axis=1))[0]
indices_0001 = np.where(np.all(treatments_3 == [0, 0, 0, 1], axis=1))[0]
# indices_1000 = np.where(np.all(treatment_last_step == [0, 0], axis=1))[0]
# indices_0100 = np.where(np.all(treatment_last_step == [1, 0], axis=1))[0]
# indices_0010 = np.where(np.all(treatment_last_step == [0, 1], axis=1))[0]
# indices_0001 = np.where(np.all(treatment_last_step == [1, 1], axis=1))[0]
# print(indices)
print(len(indices_0001))
print(len(indices_0010))
print(len(indices_0100))
print(len(indices_1000))

0
54054
54065
432492


In [ ]:
# 得到不同treatment combination下的outcome
last_predict_outcomes_1000 = last_predict_outcomes[indices_1000, :]
last_predict_outcomes_0100 = last_predict_outcomes[indices_0100, :]
last_predict_outcomes_0010 = last_predict_outcomes[indices_0010, :]
last_predict_outcomes_0001 = last_predict_outcomes[indices_0001, :]
# ground outcomes
last_ground_outcomes_1000 = last_ground_outcomes[indices_1000, :]
last_ground_outcomes_0100 = last_ground_outcomes[indices_0100, :]
last_ground_outcomes_0010 = last_ground_outcomes[indices_0010, :]
last_ground_outcomes_0001 = last_ground_outcomes[indices_0001, :]


In [ ]:
# error pehe for 0100
pehe_0100 = np.sqrt(np.mean(((last_predict_outcomes_0100-last_predict_outcomes_1000)-(last_ground_outcomes_0100-last_ground_outcomes_1000))**2))
# error pehe for 0010
pehe_0010 = np.sqrt(np.mean(((last_predict_outcomes_0010-last_predict_outcomes_1000)-(last_ground_outcomes_0010-last_ground_outcomes_1000))**2))
# error pehe for 0001
pehe_0001 = np.sqrt(np.mean(((last_predict_outcomes_0001-last_predict_outcomes_1000)-(last_ground_outcomes_0001-last_ground_outcomes_1000))**2))
pehe = (pehe_0001+pehe_0010+pehe_0100)/3
pehe

12.728578390927993